name: GuillaumeStmichel
favicon: null
layout_spectrum: 0.6569362364243716
typography_spectrum: 0.02217515790835023
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060608'
    - '#b5b5b5'
    - '#eaeaea'
    - '#868581'
    - '#3a3a3a'
  brandStrength: 0.314234078861773
  lightness: 0.8257764456793666
  saturation: 0.47685323702171445
  rhythmicContrast: 0.75
purpose: []
